- hosts: developments
  become: true
  connection: local
  user: vagrant
  vars_files:
    - group_vars/common.yml
  roles:
    - common
    - develop
    - mysql
    - git/client
    - git/prompt
    - python
    - gcloud
    - php55
