- name: install libs
  yum: name={{item}} state=installed
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel

- name: check python2.7
  shell: test -a /usr/local/bin/python2.7
  register: status
  ignore_errors: True

- name: download python2.7
  when: status|failed
  get_url: url=http://www.python.org/ftp/python/2.7/Python-2.7.tgz dest=/usr/local/src/

- name: install gcc
  yum: name=gcc state=installed

- name: compile python2.7
  when: status|failed
  shell: |
    cd /usr/local/src/
    tar fxz Python-2.7.tgz
    cd Python-2.7
    ./configure --with-threads --prefix=/usr/local
    make && make altinstall

- name: link python
  when: status|failed
  shell: |
    ln -sf /usr/local/bin/python2.7 /usr/bin/python2.7
    ln -sf /usr/local/bin/python2.7 /usr/local/bin/python2
